nume = int(input('Digite um numero para ver sua tabuada: '))
print('-'*12)
print('{} X  1 = {}'.format(nume, nume*1))
print('{} X  2 = {}'.format(nume, nume*2))
print('{} X  3 = {}'.format(nume, nume*3))
print('{} X  4 = {}'.format(nume, nume*4))
print('{} X  5 = {}'.format(nume, nume*5))
print('{} X  6 = {}'.format(nume, nume*6))
print('{} X  7 = {}'.format(nume, nume*7))
print('{} X  8 = {}'.format(nume, nume*8))
print('{} X  9 = {}'.format(nume, nume*9))
print('{} X 10 = {}'.format(nume, nume*10))
print('-'*12)